# Generated by Django 5.1.4 on 2025-02-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
